# Generated by Django 3.2.7 on 2022-05-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked', models.BooleanField()),
                ('name', models.CharField(max_length=20)),
                ('Type', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('Description', models.TextField(max_length=200)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
